language: nix

sudo: false

git:
  depth: false
  quiet: true

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - .stack-work

notifications:
  email:
    recipients:
    - florent.poinsard@epitech.eu
    on_success: never
    on_failure: always
  slack: epitech-tls-22:OsWtUSdnX45sPtL2EbBPO8aA

matrix:
  fast_finish: true
  include:
    # Add build targets here
    - env: GHCVER=8.0.2 CACHE_NAME=8.0.2
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [ghc-8.0.2], sources: [hvr-ghc]}}

    - env: GHCVER=8.2.1 CACHE_NAME=8.2.1 BUILD_BINARY=1
      compiler: ": #stack 8.2.1"
      addons: {apt: {packages: [ghc-8.2.1], sources: [hvr-ghc]}}

    - env: GHCVER=8.2.1 CACHE_NAME=8.2.1-osx BUILD_BINARY=1
      os: osx
      compiler: ": #stack 8.2.1"
      addons: {apt: {packages: [ghc-8.2.1], sources: [hvr-ghc]}}

install:
  - unset CC
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
  - ./script/install-ghr.sh
  - ./script/install-stack.sh

script:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - GHC_OPTIONS="-Werror"
  - |
    set -ex
    stack --no-terminal test --ghc-options="$GHC_OPTIONS"
    set +ex

# jobs:
#     include :
#         - stage: build
#           name: "Build"
#           script:
#             - make

#         - stage: tests
#           name: "Unit Tests"
#           script:
#             - stack --no-terminal --skip-ghc-check test

#         - stage: deploy
#           name: "Deployement"
#           if: branch IN (master, travis) AND type != cron AND type != pull_request
#           before_script:
#             - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
#             - git checkout $TRAVIS_BRANCH
#           script:
#             - git push --repo=git@git.epitech.eu:/florent.poinsard@epitech.eu/FUN_deBruijn_2018 --force